my_crm/urls.py
from django.conf.urls import url
from django.contrib import admin
from stark.service.router import site
from crm import views
urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^stark/', site.urls),
    url(r'^test/', views.test),
    url(r'^login/', views.login),
    url(r'^index/', views.index),
]

crm/models.py
from django.db import models
from rbac import models as rbac_model


class Department(models.Model):
    """
    部门表
    市场部     1000
    销售      1001
    """
    title = models.CharField(verbose_name='部门名称', max_length=16)
    code = models.IntegerField(verbose_name='部门编号',unique=True,null=False)

    def __str__(self):
        return self.title


class UserInfo(models.Model):
    """
    员工表
    """
    auth = models.OneToOneField(verbose_name='用户权限', to=rbac_model.User, null=True, blank=True)
    name = models.CharField(verbose_name='员工姓名', max_length=16)
    username = models.CharField(verbose_name='用户名', max_length=32)
    password = models.CharField(verbose_name='密码', max_length=64)
    email = models.EmailField(verbose_name='邮箱', max_length=64)
    depart = models.ForeignKey(verbose_name='部门', to="Department",to_field="code")

    def __str__(self):
        return self.name


class Course(models.Model):
    """
    课程表
    如：
        Linux基础
        Linux架构师
        Python自动化开发精英班
        Python自动化开发架构师班
    """
    name = models.CharField(verbose_name='课程名称', max_length=32)

    def __str__(self):
        return self.name


class School(models.Model):
    """
    校区表
    如：
        北京海淀校区
        北京昌平校区
        上海虹口校区
        广州白云山校区
    """
    title = models.CharField(verbose_name='校区名称', max_length=32)

    def __str__(self):
        return self.title


class ClassList(models.Model):
    """
    班级表
    如：
        Python全栈  面授班  5期  10000  2017-11-11  2018-5-11
    """
    school = models.ForeignKey(verbose_name='校区', to='School')
    course = models.ForeignKey(verbose_name='课程名称', to='Course')

    semester = models.IntegerField(verbose_name="班级(期)")
    price = models.IntegerField(verbose_name="学费")
    start_date = models.DateField(verbose_name="开班日期")
    graduate_date = models.DateField(verbose_name="结业日期", null=True, blank=True)
    memo = models.CharField(verbose_name='说明', max_length=256, blank=True, null=True, )
    teachers = models.ManyToManyField(verbose_name='任课老师', to='UserInfo', related_name='teach_classes')
    tutor = models.ForeignKey(verbose_name='班主任', to='UserInfo', related_name='classes')

    def __str__(self):
        return "{0}({1}期)".format(self.course.name, self.semester)


class Customer(models.Model):
    """
    客户表
    """
    qq = models.CharField(verbose_name='qq', max_length=64, unique=True, help_text='QQ号必须唯一')

    name = models.CharField(verbose_name='学生姓名', max_length=16)
    gender_choices = ((1, '男'), (2, '女'))
    gender = models.SmallIntegerField(verbose_name='性别', choices=gender_choices)

    education_choices = (
        (1, '重点大学'),
        (2, '普通本科'),
        (3, '独立院校'),
        (4, '民办本科'),
        (5, '大专'),
        (6, '民办专科'),
        (7, '高中'),
        (8, '其他')
    )
    education = models.IntegerField(verbose_name='学历', choices=education_choices, blank=True, null=True, )
    graduation_school = models.CharField(verbose_name='毕业学校', max_length=64, blank=True, null=True)
    major = models.CharField(verbose_name='所学专业', max_length=64, blank=True, null=True)

    experience_choices = [
        (1, '在校生'),
        (2, '应届毕业'),
        (3, '半年以内'),
        (4, '半年至一年'),
        (5, '一年至三年'),
        (6, '三年至五年'),
        (7, '五年以上'),
    ]
    experience = models.IntegerField(verbose_name='工作经验', blank=True, null=True, choices=experience_choices)
    work_status_choices = [
        (1, '在职'),
        (2, '无业')
    ]

    work_status = models.IntegerField(verbose_name="职业状态", choices=work_status_choices, default=1, blank=True,
                                      null=True)
    company = models.CharField(verbose_name="目前就职公司", max_length=64, blank=True, null=True)
    salary = models.CharField(verbose_name="当前薪资", max_length=64, blank=True, null=True)

    source_choices = [
        (1, "qq群"),
        (2, "内部转介绍"),
        (3, "官方网站"),
        (4, "百度推广"),
        (5, "360推广"),
        (6, "搜狗推广"),
        (7, "腾讯课堂"),
        (8, "广点通"),
        (9, "高校宣讲"),
        (10, "渠道代理"),
        (11, "51cto"),
        (12, "智汇推"),
        (13, "网盟"),
        (14, "DSP"),
        (15, "SEO"),
        (16, "其它"),
    ]
    source = models.SmallIntegerField('客户来源', choices=source_choices, default=1)
    referral_from = models.ForeignKey(
        'self',
        blank=True,
        null=True,
        verbose_name="转介绍自学员",
        help_text="若此客户是转介绍自内部学员,请在此处选择内部学员姓名",
        related_name="internal_referral"
    )
    course = models.ManyToManyField(verbose_name="咨询课程", to="Course")

    status_choices = [
        (1, "已报名"),
        (2, "未报名")
    ]
    status = models.IntegerField(
        verbose_name="状态",
        choices=status_choices,
        default=2,
        help_text=u"选择客户此时的状态"
    )
    consultant = models.ForeignKey(verbose_name="课程顾问", to='UserInfo', related_name='consultant',limit_choices_to={'depart_id':1001})
    date = models.DateField(verbose_name="咨询日期", auto_now_add=True)
    recv_date = models.DateField(verbose_name='接客时间', null=True, blank=True)

    last_consult_date = models.DateField(verbose_name="最后跟进日期", auto_now_add=True)

    def __str__(self):
        return "姓名:{0},QQ:{1}".format(self.name, self.qq, )


class CustomerDistribution(models.Model):
    """
    客户分配表
    """
    user = models.ForeignKey(verbose_name='客户顾问',to='UserInfo',related_name='cds',limit_choices_to={'depart_id':1000})
    customer = models.ForeignKey(verbose_name='客户',to='Customer',related_name='dealers')
    ctime = models.DateField()
    status_choices = (
        (1,'正在跟进'),
        (2,'已成单'),
        (3,'3天未跟进'),
        (4,'15天未成单'),
    )
    status = models.IntegerField(verbose_name='状态',choices=status_choices,default=1)
    memo = models.CharField(verbose_name='更多信息',max_length=255)


class SaleRank(models.Model):
    """
    销售权重和数量
    """
    user = models.ForeignKey(to="UserInfo",limit_choices_to={'depart_id':1001})
    num = models.IntegerField(verbose_name='数量')
    weight = models.IntegerField(verbose_name='权重')


class ConsultRecord(models.Model):
    """
    客户跟进记录
    """
    customer = models.ForeignKey(verbose_name="所咨询客户", to='Customer')
    consultant = models.ForeignKey(verbose_name="跟踪人", to='UserInfo')
    date = models.DateField(verbose_name="跟进日期", auto_now_add=True)
    note = models.TextField(verbose_name="跟进内容...")


class PaymentRecord(models.Model):
    """
    缴费记录
    """
    customer = models.ForeignKey(Customer, verbose_name="客户")

    class_list = models.ForeignKey(verbose_name="班级", to="ClassList", blank=True, null=True)

    pay_type_choices = [
        (1, "订金/报名费"),
        (2, "学费"),
        (3, "转班"),
        (4, "退学"),
        (5, "退款"),
    ]
    pay_type = models.IntegerField(verbose_name="费用类型", choices=pay_type_choices, default=1)
    paid_fee = models.IntegerField(verbose_name="费用数额", default=0)
    turnover = models.IntegerField(verbose_name="成交金额", blank=True, null=True)
    quote = models.IntegerField(verbose_name="报价金额", blank=True, null=True)
    note = models.TextField(verbose_name="备注", blank=True, null=True)
    date = models.DateTimeField(verbose_name="交款日期", auto_now_add=True)
    consultant = models.ForeignKey(verbose_name="负责老师", to='UserInfo', help_text="谁签的单就选谁")


class Student(models.Model):
    """
    学生表（已报名）
    """
    customer = models.OneToOneField(verbose_name='客户信息', to='Customer')

    username = models.CharField(verbose_name='用户名', max_length=32)
    password = models.CharField(verbose_name='密码', max_length=64)
    emergency_contract = models.CharField(max_length=32, blank=True, null=True, verbose_name='紧急联系人')
    class_list = models.ManyToManyField(verbose_name="已报班级", to='ClassList', blank=True)

    company = models.CharField(verbose_name='公司', max_length=128, blank=True, null=True)
    location = models.CharField(max_length=64, verbose_name='所在区域', blank=True, null=True)
    position = models.CharField(verbose_name='岗位', max_length=64, blank=True, null=True)
    salary = models.IntegerField(verbose_name='薪资', blank=True, null=True)
    welfare = models.CharField(verbose_name='福利', max_length=256, blank=True, null=True)
    date = models.DateField(verbose_name='入职时间', help_text='格式yyyy-mm-dd', blank=True, null=True)
    memo = models.CharField(verbose_name='备注', max_length=256, blank=True, null=True)

    def __str__(self):
        return self.username


class CourseRecord(models.Model):
    """
    上课记录表
    """
    class_obj = models.ForeignKey(verbose_name="班级", to="ClassList")
    day_num = models.IntegerField(verbose_name="节次", help_text="此处填写第几节课或第几天课程...,必须为数字")
    teacher = models.ForeignKey(verbose_name="讲师", to='UserInfo',limit_choices_to={'depart_id__in':[1007,1008]})
    date = models.DateField(verbose_name="上课日期", auto_now_add=True)

    course_title = models.CharField(verbose_name='本节课程标题', max_length=64, blank=True, null=True)
    course_memo = models.TextField(verbose_name='本节课程内容概要', blank=True, null=True)
    has_homework = models.BooleanField(default=True, verbose_name="本节有作业")
    homework_title = models.CharField(verbose_name='本节作业标题', max_length=64, blank=True, null=True)
    homework_memo = models.TextField(verbose_name='作业描述', max_length=500, blank=True, null=True)
    exam = models.TextField(verbose_name='踩分点', max_length=300, blank=True, null=True)

    def __str__(self):
        return "{0} day{1}".format(self.class_obj, self.day_num)


class StudyRecord(models.Model):
    course_record = models.ForeignKey(verbose_name="第几天课程", to="CourseRecord")
    student = models.ForeignKey(verbose_name="学员", to='Student')
    record_choices = (('checked', "已签到"),
                      ('vacate', "请假"),
                      ('late', "迟到"),
                      ('noshow', "缺勤"),
                      ('leave_early', "早退"),
                      )
    record = models.CharField("上课纪录", choices=record_choices, default="checked", max_length=64)
    score_choices = ((100, 'A+'),
                     (90, 'A'),
                     (85, 'B+'),

templates/index.html
{% extends 'stark/layout.html' %}

{% block body %}
    <h1>欢迎登录： {{ request.session.user_info.name }}</h1>
{% endblock %}

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post">
    {% csrf_token %}

    <input type="text" name="username" />
    <input type="text" name="password" />
    <input type="submit" value="提交">
</form>
</body>
</html>

templates/multi_view.html
{% extends 'stark/layout.html' %}

{% block body %}
    <h1 >单条录入</h1>
    <a href="/static/xxx.xlsx">下载模板</a>
    <form method="post" enctype="multipart/form-data" class="form-horizontal" novalidate>
        {% csrf_token %}
        <input type="file" name="exfile">

        <input type="submit" value="提交">
    </div>
    </form>
{% endblock %}

templates/public_view.html
{% extends 'stark/layout.html' %}

{% block body %}
    <h1>公共资源</h1>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>ID</th>
                <th>QQ</th>
                <th>姓名</th>
                <th>抢单</th>
            </tr>
        </thead>
        <tbody>
            {% for row in customer_list %}
            <tr>
                <td>{{ row.id }}</td>
                <td>{{ row.qq }}</td>
                <td>{{ row.name }}</td>
                <td>
                    {% if row.consultant_id == current_user_id %}
                        <a>无权</a>
                    {% else %}
                        <a href="/stark/crm/customer/{{ row.id }}/competition/">抢单</a>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/score_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>自定义成绩录入</h1>
    <form method="post">
        {% csrf_token %}
        <table border="1">
        {% for row in data %}
            <tr>
                <td>{{ row.obj.course_record }}</td>
                <td>{{ row.obj.student }}</td>
                <td>{{ row.obj.get_record_display }}</td>
                {% for field in row.form %}
                    <td>
                        {{ field }}
                    </td>
                {% endfor %}
            </tr>
        {% endfor %}

    </table>
        <input type="submit" value="保存">
    </form>
</body>
</html>

templates/scores_view.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>所在班级</h1>
    <ul id="classList" sid="{{ sid }}">
        {% for obj in class_list %}
            <li cid="{{ obj.id }}" >{{ obj.course.name }}({{ obj.semester }}期)</li>
        {% endfor %}
    </ul>
    <h1>成绩图</h1>
    <div id="container" style="width:600px;height:400px"></div>


    <script src="{% static 'jquery-1.12.4.min.js' %}"></script>
    <script src="{% static 'highcharts.js' %}"></script>
    <script>
        $(function () {
            $('#classList li').click(function () {
                var cid = $(this).attr('cid');
                var sid = $("#classList").attr('sid');
                $.ajax({
                    url:'/stark/crm/student/chart/',
                    type: 'get',
                    data: {'cid':cid,'sid':sid},
                    dataType:'JSON',
                    success:function (arg) {
                        var config = {
                            chart: {
                                type: 'column'
                            },
                            title: {
                                text: '学生成绩'
                            },
                            subtitle: {
                                text: '数据截止 2017-03，来源: <a href="https://en.wikipedia.org/wiki/List_of_cities_proper_by_population">Wikipedia</a>'
                            },
                            xAxis: {
                                type: 'category',
                                labels: {
                                    rotation: -45,
                                    style: {
                                        fontSize: '13px',
                                        fontFamily: 'Verdana, sans-serif'
                                    }
                                }
                            },
                            yAxis: {
                                min: 0,
                                title: {
                                    text: '分数'
                                }
                            },
                            legend: {
                                enabled: false
                            },
                            tooltip: {
                                pointFormat: '成绩: <b>{point.y} 百万</b>'
                            },
                            series: [{
                                name: '总人口',
                                data: [],
                                dataLabels: {
                                    enabled: true,
                                    rotation: -90,
                                    color: '#FFFFFF',
                                    align: 'right',
                                    format: '{point.y}', // one decimal
                                    y: 10, // 10 pixels down from the top
                                    style: {
                                        fontSize: '13px',
                                        fontFamily: 'Verdana, sans-serif'
                                    }
                                }
                            }]
                        };

                        config.series[0].data =arg.data;

                        //$('#container').highcharts(config);
                        Highcharts.chart('container',config);
                    }
                })
            })
        })
    </script>
</body>
</html>

templates/single_view.html
{% extends 'stark/layout.html' %}

{% block body %}
    <h1>单条录入</h1>
    <form method="post" class="form-horizontal" novalidate>
        {% csrf_token %}
        {% for field in form %}
            <div class="col-sm-6">
                <div class="form-group" style="margin-bottom: 20px;">
                    <label for="inputEmail3" class="col-sm-2 control-label">{{ field.label }}</label>
                    <div class="col-sm-10" style="position: relative">
                        <!-- 判断，如果field是ModelChoiceField，则FK； 如果是ModelMultipleChoiceField，则M2M -->
                        {{ field }}

                        <div style="position: absolute;font-size: 12px;left: 15px; right: 15px;color: #e4393c;background: #FFEBEB;">{{ field.errors.0 }}</div>
                    </div>
                </div>
            </div>
        {% endfor %}
        <div class="col-sm-offset-11 col-sm-1">
            <input type="submit" class="btn btn-primary" value="提交">
    </div>
    </form>
{% endblock %}

templates/user_view.html
{% extends 'stark/layout.html' %}

{% block body %}
    <h1>我的客户</h1>
    <table class="table table-bordered">
        <thead>
            <tr>
                <td>QQ</td>
                <td>姓名</td>
            </tr>
        </thead>
        <tbody>
            {% for row in customers %}
                <tr>
                    <td>{{ row.customer.qq }}</td>
                    <td>{{ row.customer.name }}</td>
                </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}